
# **Día 2 – NumPy aplicado**  
**Módulo 1 – Fundamentos de NumPy**  

#### En el Día 1 conocimos las bases de NumPy: entendimos qué son los arrays, cómo se diferencian de las listas, aprendimos sobre sus propiedades y realizamos operaciones básicas.

### Ahora bien, seguramente ayer te preguntaste algo como:
- #### Está buenísimo tener arrays… pero ¿cómo hago para sacar solo una parte de ellos? ¿Cómo selecciono valores específicos?
- #### ¿Y si quiero comparar arrays entre sí? ¿Cómo sumo, resto o filtro datos grandes sin tener que escribir 100 líneas de código?

### Justamente esas preguntas son la puerta de entrada al Día 2.

### Hoy vamos a trabajar con:

- #### Indexación y slicing → cómo acceder a elementos y fragmentos de un array, igual que cuando cortamos una torta en porciones.

- #### Operaciones entre arrays → cómo combinar y comparar datos de forma súper rápida y eficiente.

- #### Caso práctico: segmentar préstamos en rangos → llevar todo a un ejemplo financiero real, como si tuviéramos que clasificar clientes según el monto que pidieron.

#### Al final del día, vas a tener la habilidad de “sacarle jugo” a cualquier dataset grande usando NumPy, seleccionando y transformando la información que realmente te importa.

---


##  Objetivos del dia
- #### Dominar **indexación** (elegir elementos puntuales) y **slicing** (cortar porciones) en arrays 1D y 2D.
- #### Aplicar **operaciones entre arrays** (suma, resta, multiplicación, comparaciones) de forma vectorizada.
- #### Resolver un **caso práctico**: **segmentación de préstamos en rangos** con máscaras booleanas.



---
#  — **Indexación y Slicing**

#### 

### Indexación

#### Indexación es cuando elegís un elemento puntual de una estructura que guarda datos, como una lista, un array o un texto.
#### Es como si tuvieras una fila de casilleros numerados, y vos dijeras: “quiero abrir el casillero número 4”. Solo abrís ese y ves lo que hay adentro.

### En pocas palabras: indexar es apuntar a un dato específico usando su posición.

---

### Slicing

#### Slicing es cuando no querés un solo dato, sino un pedazo entero de la estructura.
#### Es como tener una biblioteca con muchos libros en fila y decir: “quiero desde el libro 3 hasta el libro 7”. No te quedás con uno, sino con una sección entera y seguida.

### En pocas palabras: hacer slicing es cortar y quedarte con un tramo de datos contiguos.
---


## 1. Necesidad

#### Imaginá que tenés una tabla enorme con ventas diarias de un supermercado durante un año.
#### Son 365 números en un array.

### Ahora te pido:

- #### Mostrame solo la venta del día 1.

- #### Después, mostrame la venta de la semana 1 (los primeros 7 días).

- #### Ahora, mostrame solo los días del 100 al 120.

#### Si tuvieras que hacerlo con una lista de Python a mano, sería un lío estar contando índices y cortando pedacitos todo el tiempo.

#### Ahí aparece la necesidad: poder seleccionar partes de un array de forma rápida, ordenada y sin esfuerzo manual.
---

## 2. Indexacion y slicing

#### Para eso existe en NumPy la indexación y el slicing.

#### Indexación → acceder a un elemento puntual.

#### Slicing → cortar un fragmento del array (como un “rebanado”).
---

## 3. Concepto

#### En un array, los elementos se guardan en posiciones llamadas índices.

#### El primer elemento siempre tiene índice 0.

#### Con indexación, elegimos un valor puntual.

#### Con slicing, elegimos un rango de valores (del inicio al final que indiquemos).

### En análisis de datos, esto es vital porque rara vez trabajamos con todo el dataset a la vez. Generalmente necesitamos:

- #### Ver un subconjunto.

- #### Filtrar días, meses, regiones o clientes específicos.

- #### Comparar segmentos entre sí.
---

## 4. Ejemplo de muestra

In [1]:
import numpy as np

ventas = np.array([100, 200, 150, 300, 250, 400, 350])

# Indexación: acceder al primer día
print("Venta del día 1:", ventas[0])

# Slicing: acceder a los primeros 3 días
print("Ventas de los días 1 a 3:", ventas[0:3])

# Slicing: acceder del día 3 al final
print("Ventas desde el día 3 en adelante:", ventas[2:])

# Slicing con salto (step): cada 2 días
print("Ventas día por medio:", ventas[::2])


Venta del día 1: 100
Ventas de los días 1 a 3: [100 200 150]
Ventas desde el día 3 en adelante: [150 300 250 400 350]
Ventas día por medio: [100 150 250 350]


## 5. Explicación del ejemplo

- ### ventas[0] → muestra 100, porque es el primer elemento (índice 0).

- ### ventas[0:3] → va desde índice 0 hasta 2 (el 3 no se incluye) → [100, 200, 150].

- ### ventas[2:] → desde índice 2 hasta el final → [150, 300, 250, 400, 350].

- ### ventas[::2] → agarra todo el array pero de 2 en 2 → [100, 150, 250, 350].
---

## 6. Ejercicio para los alumnos

### Con el siguiente array de temperaturas semanales:

### `temperaturas = np.array([30, 32, 28, 35, 31, 29, 33])`

- #### 1. Mostrá la temperatura del primer día.

- #### 2. Mostrá las temperaturas de los días 2 a 5.

- #### 3. Mostrá todas las temperaturas menos la primera y la última.

- #### 4. Mostrá solo los días pares (2, 4, 6).


# Indexación y slicing en arrays 2D

#### **Indexación**

#### Concepto: es agarrar un elemento específico en una secuencia usando su posición (su índice). Python comienza a contar desde 0: el primer elemento está en la posición 0, el siguiente en la 1 y así.

#### **Slicing**

#### Concepto: es agarrar un sub-conjunto (una parte) de una secuencia indicando dónde empieza y dónde termina, usando dos puntos (:). El tramo incluye el índice donde arranca, pero no incluye el que indica dónde termina.

## 1. Necesidad

#### Imaginá que trabajás en un banco y tenés una tabla con préstamos:

| Cliente | Monto | Plazo (meses) |
| ------- | ----- | ------------- |
| Ana     | 1000  | 12            |
| Luis    | 2000  | 24            |
| Sofía   | 1500  | 18            |


### **Ahora necesitás:**

- #### Ver solo el monto del primer cliente.

- #### Ver todos los plazos.

- #### Ver las dos primeras filas completas.

#### Si intentaras hacer esto con listas anidadas en Python, tendrías que andar escribiendo [0][1], recorrer con bucles, etc. Muy poco práctico.

#### Por eso necesitamos una forma clara y directa de acceder a filas, columnas o subconjuntos completos.
---

##  Indexación y slicing en arrays 2D
#### En arrays 2D, NumPy permite indexar con dos posiciones:

- #### La primera es la fila.

- #### La segunda es la columna.

### Sintaxis: `array[fila, columna].`


## 3. Concepto

#### Un **array 2D** en NumPy es como una **tabla de Excel**:

- ####  Está formado por **filas** (horizontal) y **columnas** (vertical).
- ####  Cada valor tiene una posición definida: primero la **fila** y luego la **columna**.

#### Ejemplo: `array[0, 0]` → fila 0, columna 0 → primer valor de la tabla.

### La idea es la misma que en arrays 1D, pero ahora trabajamos con dos coordenadas.

---

### **¿Qué podemos hacer con indexación y slicing en 2D?**

- #### Acceder a **un solo valor puntual** → como leer una celda de Excel.
- #### Seleccionar **una fila completa** → todos los datos de un cliente, alumno o registro.
- #### Seleccionar **una columna completa** → todos los montos, todas las edades, todas las notas.
- #### Tomar **un bloque (submatriz)** → porciones rectangulares de la tabla, como si copiaras una parte de Excel.

---

### En análisis de datos esto es clave porque casi siempre trabajamos con información tabular (datasets). Con indexación y slicing podemos:

- #### Ver rápidamente solo los datos que nos interesan.
- #### Separar información en partes para analizar mejor.
- #### Preparar subconjuntos para aplicar filtros, cálculos o gráficos.

## En resumen:

- #### **1D** = lista de valores (una sola dimensión).
- #### **2D** = tabla con filas y columnas (dos dimensiones).
- #### El concepto es el mismo: elegir posiciones → pero en 2D necesitamos **dos coordenadas** (fila y columna).

---


# 4. Ejemplo de muestra

In [2]:
import numpy as np

prestamos = np.array([
    [1000, 12],
    [2000, 24],
    [1500, 18]
])

# Indexación: monto del primer cliente (fila 0, columna 0)
print("Monto del primer cliente:", prestamos[0, 0])

# Indexación: plazo del segundo cliente (fila 1, columna 1)
print("Plazo del segundo cliente:", prestamos[1, 1])

# Slicing: todas las filas, solo la columna de plazos
print("Plazos de todos los clientes:", prestamos[:, 1])

# Slicing: las dos primeras filas, todas las columnas
print("Dos primeros clientes:\n", prestamos[0:2, :])

# Slicing: todas las filas, solo la primera columna (montos)
print("Montos de todos los clientes:", prestamos[:, 0])


Monto del primer cliente: 1000
Plazo del segundo cliente: 24
Plazos de todos los clientes: [12 24 18]
Dos primeros clientes:
 [[1000   12]
 [2000   24]]
Montos de todos los clientes: [1000 2000 1500]


## 5. Explicación del ejemplo

### Indexación = agarrar un dato puntual:

* **`prestamos[0, 0]`**

  * Fila 0 (primera) y columna 0 (primera).
  * vas al elemento por **posición exacta**.
  * Resultado: **1000**.

* **`prestamos[1, 1]`**

  * Fila 1 (segunda) y columna 1 (segunda).
  * De nuevo, posición precisa.
  * Resultado: **24**.

### Slicing = agarrar un tramo (una parte continua):

* **`prestamos[:, 1]`**

  * `:` en filas: **todas** las filas (desde 0 hasta el final).
  * `1` en columna: solo la segunda columna.
  * acá indico un tramo (todas las filas), y elijo una posición fija sobre columnas.
  * Resultado: todos los plazos → `[12, 24, 18]`.

* **`prestamos[0:2, :]`**

  * `0:2` en filas: fila 0 **inclusiva** hasta fila 2 **excluida** → filas 0 y 1.
  * `:` en columna: todas las columnas.
  * Con slicing estás pidiendo “una sección de la tabla, filas 0 y 1 completas.

* **`prestamos[:, 0]`**

  * `:` en filas = todas las filas.
  * `0` en columna = solo la primera columna.
  * Resultado: todos los montos → `[1000, 2000, 1500]`.

| Acción                     | Qué hacés en palabras claras                             | Analogía rápida                      |
| -------------------------- | -------------------------------------------------------- | ------------------------------------ |
| **Indexación**             | Agarrás un dato preciso por su posición                  | “Voy al casillero exacto”            |
| **Slicing filas (`0:2`)**  | Agarrás filas 0 y 1 (2 no se incluye)                    | “Quiero solo las dos primeras filas” |
| **Slicing columnas (`:`)** | Todas las columnas                                       | “Dame todo lo que hay”               |
| **Poner `:` en filas**     | Elegís todas las filas, desde la primera hasta la última | “Dame a todas las personas”          |


## 6. Ejercicios para los alumnos

#### Con el siguiente array que representa las ventas (en USD) de 4 tiendas durante 5 días:


In [ ]:
import numpy as np

ventas = np.array([
    [120, 135, 150, 160, 170],   # Tienda 1
    [200, 210, 190, 220, 230],   # Tienda 2
    [90,  100, 95,  110, 105],   # Tienda 3
    [300, 320, 310, 305, 315]    # Tienda 4
])


## Ejercicios:

- #### Mostrá la venta del tercer día de la Tienda 2.

- #### Mostrá todas las ventas de la Tienda 4.

- #### Mostrá todas las ventas del primer día (todas las tiendas).

- #### Mostrá las ventas de las Tiendas 1 y 2 durante los primeros 3 días.

- #### Mostrá las ventas de la Tienda 3, excepto el primer y el último día.

- #### Mostrá todas las ventas de las Tiendas 2 y 4, pero solo en los días 2 y 4.

- #### Mostrá el bloque central de la tabla: filas 1 y 2 (Tienda 2 y 3) y columnas 1 a 3 (días 2, 3 y 4).

# Operaciones entre arrays

## 1. La necesidad

### Imaginá esta situación: trabajás en un banco y tenés:

- #### un array con los montos de préstamos que se entregaron,

- #### otro array con los intereses aplicados,

- #### y ahora querés saber cuánto debe devolver cada cliente.

#### Si tuvieras que hacerlo con listas normales de Python, tendrías que armar bucles, multiplicar uno por uno, acumular en una lista nueva… demasiado trabajo y poco claro.

#### Con NumPy, las operaciones son automáticas: podés sumar, restar, multiplicar y dividir arrays completos de una sola vez, como si fueran una calculadora gigante.

#### Esto hace que el análisis sea rápido, limpio y fácil de leer.
---

## 2. El concepto

### Cuando trabajamos con arrays en NumPy:

- #### Una operación matemática aplicada a un array se hace elemento por elemento (vectorización).

- #### Los operadores son los mismos que en matemáticas (+, -, *, /, **).

- #### También podemos hacer comparaciones (>, <, ==) y obtener arrays de valores booleanos (verdadero/falso).

#### La condición: los arrays deben tener la misma forma (shape).
#### Si no la tienen, entra en juego algo llamado broadcasting (que veremos más adelante).
---

## 3. Ejemplo práctico

In [1]:
import numpy as np

# Montos de préstamos
montos = np.array([1000, 2000, 1500])

# Intereses en porcentaje
intereses = np.array([0.10, 0.15, 0.20])

# Cálculo: total a pagar = monto + monto*interés
total = montos + (montos * intereses)

print("Montos:", montos)
print("Intereses:", intereses)
print("Total a pagar:", total)

# Comparaciones
print("¿El primer cliente paga más que el segundo?", total[0] > total[1])
print("¿Algún cliente paga exactamente 1800?", 1800 in total)


Montos: [1000 2000 1500]
Intereses: [0.1  0.15 0.2 ]
Total a pagar: [1100. 2300. 1800.]
¿El primer cliente paga más que el segundo? False
¿Algún cliente paga exactamente 1800? True


## 4. Explicación

#### 1. montos * intereses

- #### Multiplica cada elemento del array montos por su par en intereses.

- #### Resultado: [100, 300, 300] → son los intereses de cada préstamo.

#### 2. montos + (montos * intereses)

- #### Suma el monto original con los intereses calculados.

- #### Resultado: [1100, 2300, 1800].

#### 3. Comparación total[0] > total[1]

- #### ¿1100 es mayor que 2300? → False.

#### Comparación 1800 in total

- #### Busca si existe exactamente ese valor en el array.

- #### Como está, devuelve True.
---

## 5. Más ejemplos rápidos

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   
print(a - b)  
print(a * b)  
print(a / b)  
print(a ** 2) 
print(a > 2)   


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[False False  True]


#### cada operación se aplica a todos los elementos a la vez.
---

## 6. Ejercicios para los alumnos

#### Crear dos arrays:

- #### uno con los sueldos base de 5 empleados,

- #### otro con los bonos que recibieron.
- #### Calcular el sueldo total de cada empleado.

#### Crear un array con temperaturas en °C y convertir todas a °F usando la fórmula:

- #### `𝐹 = 𝐶 × 1.8 + 32`


#### Dado un array con ventas de 6 días, calcular el promedio diario y verificar si algún día se vendió exactamente el doble del promedio.

#### Crear un array con las edades de 8 personas y:

- #### sumar 1 año a todas (nuevo año).

- #### verificar cuáles son mayores de 18.

### 1er ejercicio 
#### Sueldos + bonos → sueldo total por empleado

In [3]:
import numpy as np

sueldos = np.array([1000, 1200, 1100, 950, 1300])  
bonos   = np.array([100,  200,    0,  50,  150])    

totales = sueldos + bonos

print("Sueldos base:", sueldos)
print("Bonos:", bonos)
print("Sueldo total:", totales)


Sueldos base: [1000 1200 1100  950 1300]
Bonos: [100 200   0  50 150]
Sueldo total: [1100 1400 1100 1000 1450]


### 2do ejercicio
#### Temperaturas °C → °F (F = C × 1.8 + 32)

In [5]:
C = np.array([20, 25.5, 0, -5, 30], dtype=float)
F = C * 1.8 + 32

print("°C:", C)
print("°F:", F)

'''
La operación C * 1.8 + 32 se aplica a todos los elementos del array de una vez (vectorización). No hay bucles manuales.
'''


°C: [20.  25.5  0.  -5.  30. ]
°F: [68.  77.9 32.  23.  86. ]


'\nLa operación C * 1.8 + 32 se aplica a todos los elementos del array de una vez (vectorización). No hay bucles manuales.\n'

## 3) Ventas de 6 días → promedio y “¿algún día vendió el doble del promedio?”

In [8]:
ventas = np.array([50, 100, 200, 80, 70, 100], dtype=float)

promedio = ventas.mean()
doble_prom = 2 * promedio

print("Ventas:", ventas)
print("Promedio:", promedio)
print("Doble del promedio:", doble_prom)

# comparación directa
resultado = ventas == doble_prom
print("¿Cada día es el doble del promedio?:", resultado)

# extra: comprobar si existe al menos un True
print("¿Existe algún día con el doble del promedio?:", True in resultado)



Ventas: [ 50. 100. 200.  80.  70. 100.]
Promedio: 100.0
Doble del promedio: 200.0
¿Cada día es el doble del promedio?: [False False  True False False False]
¿Existe algún día con el doble del promedio?: True


## 4) Edades → sumar 1 año y marcar mayores de 18

In [7]:
edades = np.array([17, 18, 22, 15, 30, 19, 12, 45])
edades_mas_1 = edades + 1
mayores_18 = edades_mas_1 > 18            

print("Edades originales:", edades)
print("Edades + 1 año:", edades_mas_1)
print("¿Mayores de 18?:", mayores_18)
print("Edades (solo mayores):", edades_mas_1[mayores_18])


Edades originales: [17 18 22 15 30 19 12 45]
Edades + 1 año: [18 19 23 16 31 20 13 46]
¿Mayores de 18?: [False  True  True False  True  True False  True]
Edades (solo mayores): [19 23 31 20 46]


# Caso práctico: segmentar préstamos en rangos

## 1) Necesidad

#### Imaginá que trabajás en un banco.
#### Tenés una tabla con préstamos: cada fila representa a un cliente, y cada préstamo tiene un monto en dinero.

#### Tu jefa te pide:

- #### separar los préstamos en pequeños, medianos y grandes,

- #### contar cuántos hay en cada grupo,

- #### y calcular el promedio de monto por cada grupo.

#### Hacer esto “a mano” (mirando uno por uno y decidiendo si es chico, mediano o grande) sería imposible si tenés miles de clientes.
#### Necesitamos una forma rápida y automática.
### `Para eso usamos segmentación en rangos con NumPy.`
---

## 2) El concepto

#### Segmentar en rangos significa dividir un conjunto de valores en categorías según intervalos numéricos.

### Ejemplo cotidiano:

#### En la escuela, las notas se dividen en rangos:

- #### 1 a 3 → desaprobado

- #### 4 a 6 → aprobado justo

- #### 7 a 10 → excelente

#### Hacemos lo mismo con los préstamos:

- #### de 0 a 5000 → préstamo pequeño

- #### de 5001 a 20000 → préstamo mediano

- #### más de 20000 → préstamo grande

#### Esto sirve para analizar datos más fácilmente.
#### En lugar de mirar cada número, miramos categorías.
---

## 3) Cómo lo resolvemos

#### NumPy nos da funciones que ayudan:

- #### np.where → sirve para poner condiciones y devolver un resultado según esa condición.
#### *Ejemplo:* “si el monto es menor a 5000, poner ‘Pequeño’, si no, poner ‘Grande’”.

- #### np.digitize → sirve para asignar cada número a un rango automáticamente, según límites que le damos.
---

## 4) Ejemplo en código
#### Primero creamos un array con montos de préstamos:

In [9]:
import numpy as np

prestamos = np.array([1000, 3000, 7000, 15000, 25000, 50000])


#### Ahora segmentamos en 3 rangos:

- #### Pequeño: 0–5000

- #### Mediano: 5001–20000

- #### Grande: más de 20000

### *Usamos np.where:*

In [10]:
categorias = np.where(prestamos <= 5000, "Pequeño",
            np.where(prestamos <= 20000, "Mediano", "Grande"))

print(categorias)


['Pequeño' 'Pequeño' 'Mediano' 'Mediano' 'Grande' 'Grande']


## 5) Explicación del ejemplo

#### prestamos: es el array con montos.

#### np.where(condición, valor_si_verdadero, valor_si_falso):

#### Primero mira si el préstamo es menor o igual a 5000.

#### Si es cierto, le pone “Pequeño”.

#### Si no, pasa a la segunda condición: ¿es menor o igual a 20000?

#### Si sí, le pone “Mediano”.

#### Si no, le pone “Grande”.

### Es como un semáforo con varias luces:

- #### si es rojo, pará → Pequeño,

- #### si es amarillo, cuidado → Mediano,

- #### si es verde, seguí → Grande.
---

## 6) Conteo y promedio por grupo
### Ahora que tenemos categorías, podemos agrupar y sacar estadísticas:

In [ ]:
for categoria in ["Pequeño", "Mediano", "Grande"]:
    prestamos_categoria = prestamos[categorias == categoria]
    print(categoria, "→ cantidad:", len(prestamos_categoria), "→ promedio:", prestamos_categoria.mean())


Pequeño → cantidad: 2 → promedio: 2000.0
Mediano → cantidad: 2 → promedio: 11000.0
Grande → cantidad: 2 → promedio: 37500.0


## 7) Ejemplo con edades de personas
#### Guarda solo las edades que son de la categoría “adulto”.

In [12]:
edades = np.array([5, 12, 17, 25, 40])
categorias = np.array(["niño", "niño", "adolescente", "adulto", "adulto"])

categoria = "adulto"
edades_categoria = edades[categorias == categoria]
print(edades_categoria)


[25 40]


# 8) Ejemplo con temperaturas
#### Guarda solo las temperaturas que son de la categoría “templado”.

In [13]:
temperaturas = np.array([10, 18, 25, 30, 35])
categorias = np.array(["frío", "templado", "templado", "calor", "calor"])

categoria = "templado"
temps_categoria = temperaturas[categorias == categoria]
print(temps_categoria)


[18 25]


# 9) Ejercicios para practicar

#### Usá este array de préstamos: `[2000, 4500, 6000, 12000, 18000, 22000, 40000]`.
#### Segmentalo en Pequeño (<=5000), Mediano (5001–20000), Grande (>20000).

### Cambiá los rangos:

- #### 0–10000 → Bajo,

- #### 10001–30000 → Medio,

- #### más de 30000 → Alto.

### Calculá:

- #### cuántos préstamos son “Altos”,

- #### cuál es el promedio de los “Bajos”.
---

# Resolver ejercicio

In [15]:
import numpy as np

# 1) Creamos el array con los montos de los préstamos
prestamos = np.array([2000, 4500, 6000, 12000, 18000, 22000, 40000])

# 2) Clasificamos cada préstamo en una categoría (Bajo, Medio, Alto)
categorias = np.where(prestamos <= 10000, "Bajo", # - Si es menor o igual a 10000 → "Bajo"
            np.where(prestamos <= 30000, "Medio", "Alto"))# - Si no, pero menor o igual a 30000 → "Medio" -- # - Si no, entonces → "Alto"

# Ahora categorias contiene algo así:
# ['Bajo' 'Bajo' 'Medio' 'Medio' 'Medio' 'Medio' 'Alto']

# 3a) Filtramos los préstamos que son "Altos"
# categorias == "Alto" devuelve un array de True/False
altos = prestamos[categorias == "Alto"]

print("Cantidad de Altos:", len(altos))

# 3b) Filtramos los préstamos que son "Bajos"
bajos = prestamos[categorias == "Bajo"]

# Calculamos el promedio de los préstamos "Bajos"
print("Promedio de Bajos:", bajos.mean())


Cantidad de Altos: 1
Promedio de Bajos: 4166.666666666667


# 9) Ejercicio: Segmentar salarios
## Contexto

#### Imaginá que trabajás en el área de Recursos Humanos de una empresa.
#### Tenés una lista con los salarios mensuales de los empleados.

#### Querés dividirlos en 3 grupos:

- #### Bajo: hasta 3000

- #### Medio: de 3001 a 7000

- #### Alto: más de 7000

#### Después, necesitás responder:

- #### ¿Cuántos empleados ganan en la categoría Media?

- #### ¿Cuál es el promedio de salarios Altos?

In [16]:
import numpy as np

# salarios de empleados
salarios = np.array([1500, 2800, 3500, 5000, 7200, 10000, 4500, 8000])

# clasificar en Bajo, Medio, Alto
categorias = np.where(salarios <= 3000, "Bajo",
            np.where(salarios <= 7000, "Medio", "Alto"))

# filtrar salarios Medios
medios = salarios[categorias == "Medio"]

# filtrar salarios Altos
altos = salarios[categorias == "Alto"]

# mostrar resultados
print("Cantidad de empleados con salario Medio:", len(medios))
print("Promedio de salarios Altos:", altos.mean())


Cantidad de empleados con salario Medio: 3
Promedio de salarios Altos: 8400.0


## Tarea para la casa: Clasificar películas por duración 

### Contexto

#### Tenés un cine que quiere analizar la duración de las películas que pasan en sus salas.
#### La idea es dividir las películas en categorías y luego hacer un análisis.

### Datos

#### Duraciones de películas en minutos:


#### `duraciones = np.array([80, 95, 120, 150, 110, 200, 75, 130, 160])`


### Lo que deben hacer

#### 1. Crear categorías:

- ####   **Corta**: hasta 90 minutos
- ####   **Media**: entre 91 y 140 minutos
- ####   **Larga**: más de 140 minutos

### 2. Calcular:

- ####   Cuántas películas son **Largas**.
- ####   Cuál es el **promedio de duración** de las películas **Medias**.

---


In [17]:
import numpy as np

# datos de las duraciones de películas
duraciones = np.array([80, 95, 120, 150, 110, 200, 75, 130, 160])

# clasificamos en Corta, Media o Larga
categorias = np.where(duraciones <= 90, "Corta",
            np.where(duraciones <= 140, "Media", "Larga"))

# filtramos las películas largas
largas = duraciones[categorias == "Larga"]

# filtramos las películas medias
medias = duraciones[categorias == "Media"]

# mostramos resultados
print("Cantidad de películas Largas:", len(largas))
print("Promedio de duración de las Medias:", medias.mean())



Cantidad de películas Largas: 3
Promedio de duración de las Medias: 113.75
