## Introducción 

Antes de empezar con el ejemplo, pensemos qué queremos lograr.

En Python ya conocemos las **listas**, que sirven para guardar varios valores. Pero cuando hablamos de análisis de datos, necesitamos algo más potente: una estructura que maneje **muchos números de manera rápida y ordenada**.

Ahí entra **NumPy** con sus **arrays numéricos**.

* Son parecidos a las listas, pero están optimizados para cálculos matemáticos.
* Guardan todos los valores del mismo tipo (por ejemplo, todos enteros).
* Y lo más importante: permiten hacer operaciones sobre todos los elementos a la vez, sin recorrerlos uno por uno.

El primer paso para trabajar con NumPy es **crear un array**. Este ejercicio nos va a mostrar cómo transformar una lista común de Python en un array NumPy y ver cómo se comporta.

---


# Crear un array de enteros

#### Primero vamos a usar NumPy, que es la librería para trabajar con arreglos numéricos.

In [5]:
# Con esto traemos NumPy y le ponemos el nombre corto np para usarlo más fácil.
import numpy as np

# creamos un array con la funcion aray() de numpay
numeros = np.array([1, 2, 3, 4, 5])


Le pasamos una lista normal de Python a la función np.array.

NumPy convierte esa lista en un array numérico, que es más rápido y eficiente.

Fíjense que todos los datos son del mismo tipo: números enteros.

In [ ]:
# Imprimir el array
print(numeros)

[1 2 3 4 5]


Esto nos devuelve [1 2 3 4 5]

Noten que no aparecen comas, porque NumPy tiene su propia forma de mostrar los datos.

Cierre del ejemplo

Lo que acabamos de hacer es transformar una lista común en un array NumPy. A partir de acá vamos a poder aplicar operaciones matemáticas a todo el conjunto de números de una sola vez.

# Array de decimales

#### No todos los datos son enteros. Muchas veces trabajamos con precios, medidas o promedios, que son decimales

In [8]:
precios = np.array([10.5, 20.0, 7.99, 15.25])
print(precios)

[10.5  20.    7.99 15.25]


##### El resultado va a ser [10.5 20. 7.99 15.25].

##### Noten que NumPy conserva los decimales tal cual y los muestra en su propio formato.

##### Con este ejemplo vemos que los arrays de NumPy no son solo para enteros: también podemos trabajar fácilmente con datos decimales, algo clave en análisis de precios, estadísticas o mediciones.


## ¿Por qué no aparece el .0 en el 20.0?

##### NumPy, cuando imprime arrays, usa un formato propio para mostrar los números.

##### Si el número no necesita mostrar decimales (como el 20.0), lo recorta y lo muestra como 20.

##### Pero internamente, el dato sigue siendo un número decimal (tipo float).

#### Es decir:

##### Lo que ves en pantalla (20) es solo la “presentación”.

##### Lo que NumPy guarda en memoria es 20.0.

---

### ¿Cómo podemos mostrar siempre los decimales?

##### Podemos decirle a NumPy que use un formato fijo para la salida:

In [20]:
np.set_printoptions(precision=1, floatmode="fixed") 
precios = np.array([10.5, 20.0, 7.99, 15.25])
print(precios)

[10.5 20.0  8.0 15.2]


#### **precision=2** → muestra 2 decimales.

#### **floatmode="fixed"** → obliga a que todos los números aparezcan con decimales, aunque sean “enteros con coma” como 20.0

---

# Array de strings

### Arrays de Strings en NumPy

#### Un array de strings es un arreglo que guarda solo texto (palabras o letras) en lugar de números.
- #### Se usa poco en NumPy, porque la librería está pensada para cálculos numéricos.
- #### Sirve cuando querés representar categorías, símbolos o letras (ejemplo: tablero de ajedrez con "B" y "N").

In [26]:
nombres = np.array(["Ana", "Luis", "Sofía", "Pedro"])
print(nombres)



letras = np.array(["A","B","C"])
print(letras)



['Ana' 'Luis' 'Sofía' 'Pedro']
['A' 'B' 'C']


### Recordatorio simple:

- #### Igual que los arrays de números, pero guardan texto.

- #### Útiles para representar cosas simbólicas, no para cálculos.

---

# Diferencia entre Lista y Array

##### Lista (Python) → es una cajita donde podés guardar de todo: números, textos, booleanos, incluso listas dentro de listas. Es flexible, pero no está pensada para hacer cuentas rápidas.

### Ejemplo: ["perro", 3, True, 5.5]

##### Array (NumPy) → es como una tabla de solo números, todos del mismo tipo (todos enteros, o todos decimales). Está optimizado para hacer cuentas muy rápido y en bloque (suma, promedio, etc.).

### Ejemplo: [1, 2, 3, 4, 5]

Idea clave:

Lista = cajón donde metés de todo.

Array = caja de herramientas ordenada y lista para matemáticas.

In [ ]:
# Ejemplo 1 – Crear una lista
lista = [1,2,3,4,5]
print(lista)
# es una lista normal de Python.

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# Multiplicar lista


In [17]:
print(lista * 2)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


##### en listas, el * repite la lista, no multiplica los valores.

# Multiplicar array

In [21]:
numeros = np.array([1, 2, 3, 4, 5])
print(numeros * 2)

[ 2  4  6  8 10]


#### Cuando hacés numeros * 2, NumPy no multiplica el array entero como si fuera un solo bloque, sino que aplica la operación a cada elemento.

#### Esto se llama vectorización: NumPy “reparte” la operación a todos los valores sin que vos tengas que escribir un bucle for.

---

#### A diferencia de las listas de Python, donde si hacés [1,2,3]*2 se repite la lista, en NumPy se hace cálculo matemático de verdad

# ejemplo de porque lista no esta optimizado para calculos matematicos

In [ ]:

lista = [1, 2, 3, 4, 5]

# para multiplicar hay que usar un bucle
resultado = []
for numero in lista:
    resultado.append(numero * 2)

print(resultado)

[2, 4, 6, 8, 10]


# Cosas para resaltar

#### Código más largo y difícil de leer

- Con listas hay que escribir varias líneas (crear lista vacía, recorrer con for, usar append).

- Con arrays, la misma tarea es una sola línea → más claro y mantenible.

#### Mayor consumo de memoria

- Las listas guardan cada elemento con su tipo de dato y referencias → ocupan más memoria.

- Los arrays de NumPy almacenan todos los valores del mismo tipo en bloques continuos de memoria → más compactos.

#### Flexibilidad vs. eficiencia

- Una lista puede mezclar datos: [1, "hola", 3.5]. Eso es útil para algunas cosas, pero ineficiente para cálculos.

- Un array solo permite un tipo → mucho más rápido en matemáticas.


---

# En una lista de Python

- Cada número se guarda como un objeto independiente.

- La lista solo guarda referencias (punteros) a esos objetos.

- Eso significa que en la memoria tenés los elementos dispersos, y Python tiene que ir “saltando” de un lugar a otro para buscarlos.

#### analogi: una mochila llena de sobres: cada sobre tiene adentro el número y un cartelito con su tipo (int, float, etc.). Para usarlos tenés que abrir cada sobre uno por uno → más lento.

# En un array de NumPy

- Todos los valores se guardan uno al lado del otro en la memoria, sin huecos.

- Además, todos son del mismo tipo (int32, float64, etc.).

- Eso permite que NumPy sepa exactamente dónde está cada valor → lee y procesa mucho más rápido.

#### Analogia: una caja de fichas ordenadas: todas iguales, alineadas, sin sobres, listas para usarse de corrido. Podés agarrar varias de un tirón → mucho más rápido.

---

# Ejercicio para practicar

- ### Crear un array con los números del 1 al 10.

- ### Sumar 5 a todos los valores.

- ### Elevar cada número al cubo.

- ### Mostrar el resultado final en pantalla.

In [2]:
import numpy as np
# paso 1 crear un array de numeros
array_de_numeros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# paso 2 sumar 5 a cada numero del array
numeros_con_suma = array_de_numeros + 5
# paso 3 elevar al cubo cada numero
numeros_elevados_al_cubo = numeros_con_suma ** 3
# paso 4 mostrar en pantall
print(numeros_elevados_al_cubo)

[ 216  343  512  729 1000 1331 1728 2197 2744 3375]


---

# Arrays 1D, 2D

## Array de 1D (una dimnsion)


##### Un **array de una dimensión** es la forma más básica de un array.

- #### Los datos están **en una sola fila**, uno detrás del otro.
- #### Se pueden recorrer de principio a fin, como si fuera una lista ordenada.
- #### Cada dato tiene una **posición** (llamada *índice*) que nos dice en qué lugar está.
- #### Es útil cuando solo necesitamos guardar datos simples que se relacionan en una sola línea: por ejemplo, las edades de un grupo de personas, las notas de un examen, o los precios de una lista de productos.

#### Lo importante es entender que en un array de 1D no hay “filas y columnas”, solo una secuencia continua.

---

## Array de 2D (dos dimensiones)

#### Un **array de dos dimensiones** ya no es solo una línea de datos.
#### Acá los valores se organizan en **filas y columnas**, como si fuera una tabla.

- #### Imaginá una hoja de cálculo o una planilla de Excel: tenés filas horizontales y columnas verticales.
- #### Para encontrar un dato no alcanza con saber su posición en una lista: ahora necesitás dos coordenadas → la **fila** y la **columna**.
- #### Esto permite representar información que naturalmente se ordena en forma de tabla, como:

  - #### notas de alumnos en diferentes materias,
  - #### precios de productos en distintas sucursales,
  - #### Temperaturas en distintas ciudades.

#### Lo clave: un array de 2D te permite ubicar datos de manera más estructurada, como en una cuadrícula.

---


# Demostración en código (rápida y clara)

## Array 1D (lo que ya hicimos)

#### Lo que tenemos acá es un array de una dimensión (1D). Es como una fila de valores, todos del mismo tipo, guardados uno al lado del otro. En este ejemplo el array tiene 5 elementos enteros.

In [3]:
import numpy as np
array_de_una_dimension = np.array([1,2,3,4,5])
print(array_de_una_dimension) 

[1 2 3 4 5]


---

## Array 2D

### Este es un array de dos dimensiones (2D). Se puede pensar como una tabla con filas y columnas, igual que en Excel.

#### 1. usamos un corchete [] para crear el array (como siempre)

#### El primer corchete grande abre y cierra todo el array.

#### Adentro metemos 3 elementos → que a su vez son listas:

- #### `[1,2,3,4]`

- #### `[5,6,7,8]`

- #### `[9,10,11,12]`

### Entonces, es un solo array, pero cada “elemento” que tiene adentro es otra lista (una fila).

### 2. Cómo pensarlo

- #### `[1,2,3,4]` = primera fila.

- #### `[5,6,7,8]` = segunda fila.

- #### `[9,10,11,12]` = tercera fila.

### Juntos forman una tabla de 3 filas × 4 columnas.
### Es lo mismo que en Excel cuando armás una cuadrícula.

In [13]:
array_de_dos_dimensiones = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(array_de_dos_dimensiones)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Ejemplo 1 - Asientos de cine
#### Vamos a pensar en un cine. Los asientos no están en una sola línea, están organizados en filas y columnas.

In [17]:
import numpy as np

asientos_de_cine = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12],
                [13,14,15,16,17,18]])
print(asientos_de_cine)
print(asientos_de_cine[1,5])
print(asientos_de_cine[1,0])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
12
7


## Asientos del cine

#### Cuando saco una entrada, me dicen ‘Fila 1, Asiento 4’. Eso son dos coordenadas: primero la fila, después el asiento dentro de esa fila.

#### `Pero en python (y programacion en general) siempre resto 1 a lo que pienso en la vida real porque Python empieza desde 0.`

### Este ejemplo es importante porque:

- ##### Nos muestra cómo un array 2D representa situaciones reales.

- ##### Nos ayuda a entender que para encontrar un dato en una tabla, no alcanza con un número (como en 1D), necesitamos dos números: fila y columna.

#### Así es como funcionan muchos sistemas: cines, aviones, estadios, teatros.

- ### Cada fila representa una fila de asientos.

- ### Cada número es un asiento dentro de esa fila.

### Para ubicar el asiento 7 → fila 1, columna 0 → [1,0].

---

# Explicación de acceso en arrays 2D

## ¿Cómo ubico un dato?

#### Para acceder a un valor uso dos coordenadas:
### `array[fila, columna]`
- #### La primera posición indica la fila.
- #### La segunda posición indica la columna.
---

#### Si quiero el primer valor de la tabla, digo [0,0].

- ##### Porque la primera fila y la primera columna empiezan en 0.

#### Si quiero el valor de la segunda fila, tercera columna, digo [1,2].

- ##### Porque la segunda fila es índice 1 y la tercera columna es índice 2.

#### Siempre resto 1 a lo que pienso en la vida real porque Python empieza desde 0.

- ##### Python cuenta desde 0

In [12]:
asientos_de_cine = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12],
                [13,14,15,16,17,18]])
print(asientos_de_cine)
print(asientos_de_cine[0,0])
print(asientos_de_cine[1,2])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
1
9


## Resumen claro :

#### Un array 2D es una tabla.

#### Para buscar un dato necesito 2 números: [fila, columna].

#### Python cuenta desde 0, así que la primera fila es 0 y la primera columna también es 0.

---

# Ejemplo 2 – Horario de clases

#### Ahora pensemos en un horario escolar.

#### No está en una sola línea: está organizado por días (filas) y horas (columnas).

In [22]:
horarios_materias = np.array([
    ['Matematica', 'Historia', 'Quimica'],
    ['Biologia', 'Fisica', 'Geometria'],
    ['Ingles', 'Quimica', 'Castellao']
])
print(horarios_materias)
print(horarios_materias[1,1])

[['Matematica' 'Historia' 'Quimica']
 ['Biologia' 'Fisica' 'Geometria']
 ['Ingles' 'Quimica' 'Castellao']]
Fisica


- ### Cada fila es un día de la semana (lunes, martes, miércoles).

- ### Cada columna es una hora del día (primera, segunda, tercera).

- ### Si quiero saber qué materia hay el martes en la segunda hora → fila 1, columna 1 → [1,1] = fisica

---
### Conclusion
- #### Con esto teenemos un ejemplo numérico (cine -> ideal para practicar coordenadas).

- #### Tenés un ejemplo con texto (horario -> muestra que los arrays sirven para mucho más que números).
---


# Ejercicios 

## Tablero de ajedrez ♟️

### Fundamento: Muestra el mismo concepto de coordenadas, pero en un tablero.

### Filas = filas del tablero.

### Columnas = columnas del tablero.

## Ejercicio

#### Crear un array 2D de 8×8 que represente un tablero de ajedrez.

#### Llenarlo con letras “B” y “N” (blanco/negro) alternados.

### Preguntar:

- #### ¿Qué color tiene la casilla en la fila 0, columna 0?

- #### ¿Qué color tiene la fila 7, columna 7?

In [23]:
# creamos un tablero (8x8) 
tablero = np.array([
    ['B','N','B','N','B','N','B','N'],
    ['N','B','N','B','N','B','N','B'],
    ['B','N','B','N','B','N','B','N'],
    ['N','B','N','B','N','B','N','B'],
    ['B','N','B','N','B','N','B','N'],
    ['N','B','N','B','N','B','N','B'],
    ['B','N','B','N','B','N','B','N'],
    ['N','B','N','B','N','B','N','B']
])
print(tablero[0,0])
print(tablero[7,7])

B
B


# Notas de alumnos 📑

### Fundamento: Ejemplo realista para arrays de números, vinculado a educación.

- #### Filas = alumnos.

- #### Columnas = exámenes.

## Ejercicio

- #### Crear un array 2D con notas de 3 alumnos en 4 exámenes.

- #### Mostrar la tabla completa.

## Preguntar:

- #### ¿Qué nota sacó el alumno 2 en el examen 3?

- #### ¿Cuál es el promedio de cada alumno (suma por fila / cantidad de columnas)?

- #### ¿Cuál es el promedio de cada examen (suma por columna / cantidad de filas)?



In [25]:
notas_de_alumnos = np.array([
    [4,3,5,2],
    [2,3,1,4],
    [5,4,3,5]
])
print(notas_de_alumnos[2,2])

3


---

# Propiedades de un array en NumPy

## ¿que es una propiedad?

#### Una propiedad es una característica fija que un objeto ya tiene guardada dentro suyo.
#### No es algo que vos calculás cada vez, sino algo que el objeto sabe de sí mismo y te lo muestra cuando lo pedís.

#### El porqué: se llama propiedad porque describe un aspecto propio, algo que lo define y que podés consultar directamente.

### Analogía:
- #### Imaginá una pelota. Su color no lo tenés que “calcular”, ya viene con ella. Si es roja, es roja siempre. 
#### Eso es una propiedad: un dato que forma parte de lo que la cosa es.
---
# 1-) shape

### 1- Necesidad

##### Cuando trabajamos con datos, lo primero que queremos saber es:
- ##### ¿Cuántas filas y columnas tengo?

#### Imaginemos una planilla de Excel de ventas:

- ##### Cada fila representa una venta (cliente, fecha, monto).

- ##### Cada columna es una característica (edad, producto, precio).

#### Si no sé cuántas filas hay, no sé si estoy analizando 10 ventas o 10.000.
#### Y si no sé cuántas columnas hay, no sé si tengo solo “precio” o también “cantidad, fecha, categoría”.

#### Entonces, lo primero que necesito es una foto general de la estructura.


## 2) Cómo lo resuelve NumPy

#### En los arrays, tenemos la propiedad `.shape`, que nos devuelve justamente esa información:
#### la forma del array (cuántas filas y cuántas columnas tiene).

### NumPy lo guarda como una tupla de números, por ejemplo:

- #### (100, 5) significa 100 filas y 5 columnas.

- #### (3, 3) significa 3 filas y 3 columnas.

## 3) Ejemplo de la vida real

### Pensá en una sala de cine:

- #### Las filas son las filas de butacas.

- #### Las columnas son los asientos de cada fila.

- #### Si la sala tiene 10 filas con 20 asientos, podemos decir: shape = (10, 20).

### No necesito recorrer todos los asientos uno por uno, simplemente veo el cartel del cine y ya sé su capacidad.
### Eso mismo hace NumPy: guarda la “forma” del array y te la devuelve al instante.
---

# 4) Ejemplo en código

In [1]:
import numpy as np

# Creamos un array 3x3
ventas = np.array([[100, 200, 300],
                [400, 500, 600],
                [700, 800, 900]])

print("Forma del array:", ventas.shape)


Forma del array: (3, 3)


# 5) Explicación detallada

#### El array tiene 3 listas internas, cada una con 3 elementos.

#### Eso significa 3 filas y 3 columnas.

#### NumPy lo expresa como (3, 3).

### `Importante: el orden siempre es (filas, columnas).`
---
# 6) Ejercicios para alumnos

- #### Crear un array de 4 filas y 5 columnas y comprobar su shape.

- #### Crear un array de una sola fila y ver cómo cambia el shape.

- #### Crear un array unidimensional (ej: [1,2,3,4,5]) y observar qué shape devuelve.

In [ ]:
import numpy as np

a = np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20]])
print(a.shape)


## devuelve (4, 5) porque son 4 filas y 5 columnas.
---

In [2]:
b = np.array([[1,2,3,4,5]])
print(b.shape)

(1, 5)


## devuelve (1, 5) porque hay 1 fila con 5 columnas.
---

In [3]:
c = np.array([1,2,3,4,5])
print(c.shape)


(5,)


## devuelve (5,) porque es un vector de 5 elementos en una sola dimensión (no tiene filas ni columnas).
---

# 2-) dtype

## 1- Necesidad

### Cuando trabajamos con datos, no es lo mismo:

- #### Guardar edades (enteros).

- #### Guardar precios (decimales).

- #### Guardar nombres (texto).

### Ejemplo: 
- #### si calculo el promedio de edad, necesito que sean enteros.
- #### Si calculo el promedio de precios, necesito decimales.
- #### Y si guardo nombres, obviamente no puedo sumarlos.

#### En una planilla de Excel, cada columna tiene un formato: número, texto, fecha.
#### En NumPy pasa lo mismo, pero de manera mucho más estricta:
#### `todo el array tiene que ser del mismo tipo de dato.`

## 2 Cómo lo resuelve NumPy

#### Con la propiedad .dtype (data type), NumPy nos dice cuál es el tipo de dato que tiene el array.

### Puede ser:

- #### int32 o int64 → números enteros.

- #### float32 o float64 → números decimales.

- #### <U → strings (texto).

## 3 Ejemplo de la vida real

### Imaginá una tabla de Excel:

- #### Si en una columna escribís solo números enteros → Excel entiende que esa columna es de enteros.

- #### Si en la misma columna ponés aunque sea un decimal → toda la columna pasa a ser de decimales.

- #### Si ponés texto en esa columna → ya no se la puede tratar como números, todo se maneja como texto.

### En NumPy:

- #### Si todos los valores son enteros → el array es de enteros (int).

- #### Si hay aunque sea un decimal → todo el array se convierte en decimales (float).

- #### Si aparece texto → todo el array pasa a texto (string).

# 4 ejemplo en codigo

In [5]:
import numpy as np

enteros = np.array([10, 20, 30])
print("Tipo de dato:", enteros.dtype)

decimales = np.array([1.5, 2.3, 3.7])
print("Tipo de dato:", decimales.dtype)

texto = np.array(["A", "B", "C"])
print("Tipo de dato:", texto.dtype)

strings_varios = np.array(['hola', 'como', 'estas'])
print(strings_varios.dtype)

mixto = np.array([10, 20.5, "hola"])
print("Tipo de dato:", mixto.dtype)


Tipo de dato: int64
Tipo de dato: float64
Tipo de dato: <U1
<U5
Tipo de dato: <U32


#### int64 → son números enteros (sin coma), que ocupan 64 bits en memoria.

#### float64 → son números decimales (con coma), también de 64 bits.

#### <U1 → es un string (texto) de hasta 1 caracter.

#### <U5 → es un string de hasta 5 caracteres.

#### <U32 → es un string de hasta 32 caracteres.

### En resumen: `dtype te dice si los datos son números o texto, y en el caso de los strings cuánto espacio máximo tienen`

# 5) Explicación detallada

### NumPy convierte automáticamente el array al tipo de dato más general posible.

- #### si hay 2 enteros y un decimal, debe convertir todo a decimal, porque un decimal no lo puede convertir a entero.

#### Si hay mezcla, “sube de nivel”:

- #### Subir de nivel en NumPy significa:
- #### Si hay mezcla, elige el tipo de dato que pueda guardar todo sin perder información.”

- - #### Enteros + decimales → todo a decimales.

- - #### Números + texto → todo a texto.

#### `Esto lo hace porque los arrays tienen que ser uniformes en memoria (más rápidos y eficientes).`

---

# 6) Ejercicios para alumnos

- ### Crear un array con solo enteros y mirar el dtype.

- ### Agregar un decimal a ese array y observar cómo cambia a float.

- ### Crear un array con texto y números → comprobar cómo todo se convierte en string.

- ### Probar con una palabra larga y observar cómo el dtype cambia de <U1 a <U10 o más.

In [ ]:
import numpy as np
solo_enteros = np.array([1,2,3,4,5, 1.1])
print(solo_enteros.dtype)

con_texto_y_numero = np.array(['primer texto', 25])
print(con_texto_y_numero.dtype)


float64
<U21


# Operaciones basicas: suma, promedio, maximo

### 1) Concepto

#### En NumPy podemos hacer operaciones matemáticas directamente sobre los arrays, sin necesidad de recorrerlos con bucles.
#### Esto se llama vectorización y lo hace mucho más rápido que con listas de Python.

### Las operaciones básicas más usadas son:

- #### Suma: juntar valores.

- #### Promedio (media): calcular el valor “típico” de un conjunto de datos.

- #### Máximo: encontrar el valor más grande.

### 2) Ejemplo de la vida real

- #### Suma → sumar todas las ventas de la semana para ver el total.

- #### Promedio → calcular cuánto se vende en promedio por día.

- #### Máximo → encontrar cuál fue el día con mayor venta.
---

### 3) Ejemplo en código

In [40]:
import numpy as np

# Ventas del dia
ventas = np.array([12.000, 34.000, 56.000, 80.000, 25.000, 40.000, 15.000])

# Operaciones básicas
total = np.sum(ventas)        # suma
promedio = np.mean(ventas)    # promedio
maximo = np.max(ventas)       # máximo

print("Ventas:", ventas)
print("Total de ventas:", total)
print("Promedio de ventas:", promedio)
print("Venta máxima:", maximo)

print('')

print(f'Total de ventas: {np.sum(ventas):.4f}')
print(f"Promedio de ventas: {np.mean(ventas):.4f}")
print(f'Venta maxima: {np.max(maximo):.4f}')



Ventas: [12.000000000000000 34.000000000000000 56.000000000000000
 80.000000000000000 25.000000000000000 40.000000000000000
 15.000000000000000]
Total de ventas: 262.0
Promedio de ventas: 37.42857142857143
Venta máxima: 80.0

Total de ventas: 262.0000
Promedio de ventas: 37.4286
Venta maxima: 80.0000


## 4) Explicación paso a paso

- #### np.sum(ventas) → recorre todos los valores y los suma.

- #### np.mean(ventas) → hace la suma total ÷ cantidad de elementos.

- #### np.max(ventas) → busca el número más grande dentro del array.

#### no necesitamos un for, NumPy lo hace directamente.

---

## 5) Ejercicios 

### Crear un array con las temperaturas de 7 días. Calcular:

- #### La temperatura total acumulada.

- #### La temperatura promedio.

- #### La temperatura más alta.

### Crear un array con los puntajes de un examen de 10 alumnos. Mostrar:

- #### La suma total de los puntajes.

- #### El promedio de la clase.

- #### El puntaje más alto.